  dist: trusty
  env:
    global:
      - MOZ_HEADLESS=1
    matrix:
      - TESTFOLDER=unit
      - TESTFOLDER=integration
      - TESTFOLDER=functional.user
      - TESTFOLDER=functional.games
  addons:
    firefox: latest
  language: python
  python:
    - "3.6"
  services: mysql
  before_install:
    - ./travis-scripts/before_install.sh
    - export PATH=$PATH:$PWD/geckodriver
  install:
    - ./travis-scripts/install.sh
  before_script:
    - export DISPLAY=:99.0
    - ./travis-scripts/before_script.sh
  script: "python manage.py test actionphase.app.tests.$TESTFOLDER"
  notifications:
    email: false
  after_failure:
    - cat /tmp/debug.log

  jobs:
  include:
    - stage: CodeDeploy Stage
      script: echo "Deploying to Stage Server..."
      deploy:
        on:
          branch: master
        provider: codedeploy
        revision_type: github
        access_key_id: $TRAVIS_AWS_ACCESS_KEY_ID
        secret_access_key: $TRAVIS_AWS_SECRET_ACCESS_KEY
        application: "ActionPhaseStage"
        deployment_group: "ActionPhaseStage"
        region: "us-east-2"