  dist: trusty
  env:
    global:
      - MOZ_HEADLESS=1
    matrix:
      - TESTFOLDER=unit
      - TESTFOLDER=integration
      - TESTFOLDER=functional
  addons:
    firefox: latest
  language: python
  python:
    - "3.6"
  services: mysql
  before_install:
    - ./travis-scripts/before_install.sh
  install:
    - ./travis-scripts/install.sh
  before_script:
    - ./travis-scripts/before_script.sh
  script: "python manage.py test houseoffun.houseoffun.tests.$TESTFOLDER"
  notifications:
    email: false
  after_failure:
    - cat /tmp/debug.log