  dist: trusty
  addons:
    chrome: stable
  language: python
  python:
    - "3.6"
  services: mysql
  # command to install dependencies
  before_install:
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  install:
    - pip install -r requirements.txt
  before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - mysql -e 'create database travis_ci;'
    - python manage.py migrate
  script:
    - python manage.py test
  notifications:
    email: false