  dist: trusty
  addons:
    chrome: stable
  language: python
  python:
    - "3.6"
  services: mysql
  # command to install dependencies
  before_install:
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:8081 &
  install:
    - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
    - unzip ~/chromedriver_linux64.zip -d ~/
    - rm ~/chromedriver_linux64.zip
    - sudo mv -f ~/chromedriver /usr/local/share/
    - sudo chmod +x /usr/local/share/chromedriver
    - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
    - pip install -r requirements.txt
  before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - python manage.py runserver &
    - sleep 3 # give xvfb some time to start
    - mysql -e 'create database travis_ci;'
    - python manage.py migrate
  script:
    - python manage.py test
  notifications:
    email: false