  language: python
  python:
    - "3.6"
  services: mysql
  # command to install dependencies
  install:
    - pip install -r requirements.txt
  before_script:
    - mysql -e 'create database travis_ci;'
    - python manage.py migrate
  script:
    - python manage.py test
  notifications:
    email: false