  language: python
  python:
    - "3.6"
  services: mysql
  # command to install dependencies
  install:
    - pip install -r requirements.txt
  before_script:
    - mysql -e 'create database houseoffun_test_db;'
    - python manage.py migrate
  script:
    - python manage.py test