version: '3'

services:
  db:
    image: mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: docker
        MYSQL_DATABASE: docker
        MYSQL_USER: docker
        MYSQL_PASSWORD: docker
  api:
    build: ./backend
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  ui:
    build: ./frontend
    command: ["npm", "run", "start"]
    volumes:
      - ./frontend:/code
      - /code/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - api